export const fillScreen: string;
export const container: string;
export const white: string;
export const start: string;
export const banner: string;
export const receiptContainer: string;
export const qrcode: string;
export const ctaWrapper: string;
export const cta: string;
